In [1]:
import numpy as np
import pandas as pd

In [2]:
from myproject import LSHkCenters

In [3]:
X = np.array(
    [[0, 0, 0], [0, 1, 1], [0, 0, 0], [1, 0, 1], [2, 2, 2], [2, 3, 2], [2, 3, 2]]
)
y = np.array([0, 0, 0, 0, 1, 1, 1])

In [4]:
# data = pd.read_csv("datasets/soybean-small.data.csv", header=None)
# X = data.iloc[:, :-1].values
# y = data.iloc[:, -1].values
# # y has values [D1,D2,D3,D4] but we need [0,1,2,3]
# y = np.unique(y, return_inverse=True)[1]

In [5]:
kcens = LSHkCenters(X, y, n_init=5, k=2)
#kcens.do_cluster()

X [[0 0 0]
 [0 1 1]
 [0 0 0]
 [1 0 1]
 [2 2 2]
 [2 3 2]
 [2 3 2]]
SU_matrix [[0.         0.60689525 0.58669983]
 [0.48219867 0.         0.530354  ]
 [0.56402686 0.63104655 0.        ]]
context_Y [[0 0]
 [1 1]
 [0 0]
 [0 1]
 [2 2]
 [3 2]
 [3 2]]


IndexError: tuple index out of range