In [1]:
import numpy as np
import pandas as pd

In [2]:
from myproject import LSHkCenters

In [3]:
X = np.array(
    [[0, 0, 0], [0, 1, 1], [0, 0, 0], [1, 0, 1], [2, 2, 2], [2, 3, 2], [2, 3, 2]]
)
y = np.array([0, 0, 0, 0, 1, 1, 1])

In [4]:
# data = pd.read_csv("datasets/soybean-small.data.csv", header=None)
# data = data.apply(lambda col: pd.factorize(col)[0])
# X = data.iloc[:, :-1].values
# y = data.iloc[:, -1].values
# y = np.unique(y, return_inverse=True)[1]


In [5]:
X

array([[0, 0, 0],
       [0, 1, 1],
       [0, 0, 0],
       [1, 0, 1],
       [2, 2, 2],
       [2, 3, 2],
       [2, 3, 2]])

In [6]:
kcens = LSHkCenters(X, y, n_init=5, k=2)
#kcens.do_cluster()

X
 [[0 0 0]
 [0 1 1]
 [0 0 0]
 [1 0 1]
 [2 2 2]
 [2 3 2]
 [2 3 2]]
SU_matrix
 [[       nan 0.60689525 0.58669983]
 [0.48219867        nan 0.530354  ]
 [0.56402686 0.63104655        nan]]
dist_matrices
 [array([[0.        , 0.28571429, 0.53452248],
       [0.28571429, 0.        , 0.45175395],
       [0.53452248, 0.45175395, 0.        ]]), array([[0.        , 0.28571429, 0.34992711, 0.42857143],
       [0.28571429, 0.        , 0.20203051, 0.31943828],
       [0.34992711, 0.20203051, 0.        , 0.14285714],
       [0.42857143, 0.31943828, 0.14285714, 0.        ]]), array([[0.        , 0.20203051, 0.51507875],
       [0.20203051, 0.        , 0.47380354],
       [0.51507875, 0.47380354, 0.        ]])]
